# https://yarnpkg.com/getting-started/install
# https://yarnpkg.com/configuration/yarnrc
# https://yarnpkg.com/features/zero-installs

# https://yarnpkg.com/features/pnp
nodeLinker: pnpm

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.0.cjs

enableGlobalCache: true
